### ISSUE TITLE
puppet-maint gem doesn't exist

### ISSUE THREAD

**Issue by EslamElHusseiny** [liamjbennett/puppet-maint#1]
seems like there is not puppet-maint gem 

ERROR:  Could not find a valid gem 'puppet-maint' (>= 0) in any repository

**Comment by liamjbennett** [comment]
Hi,
No I have not released this yet. It is very alpha and I wanted to gather a bit of community feedback before releasing the gem.

Thanks for taking the time to look at this project.

**Comment by EslamElHusseiny** [comment]
:+1:

**Comment by gyles19** [comment]
I just inherited a several-years-old puppet master that is in desperate need of cleaning.  The puppet-dashboard had over 4M reports in it, which took hours to prune.  I know there are tons of flat files and other things that need help.  Unfortunately, I know zilch about ruby, gems, and so forth (I do perl, though.)  All of the puppet-related stuff on the master was installed from ubuntu packages.  I need ruby-noob-level directions on how to accomplish anything with this gem here, sadly.

I can do git clones and such, but when I attempted to gem build...; gem install --local ... I got another error about dependencies so I've given up.  I'm guessing the gem command expected to see puppet installed as a gem, not as a deb package, so it fails there.

**Comment by liamjbennett** [comment]
Sorry you had a bad experience here. You might actually be the first person other than me to use this tool. 

In terms of the puppet gem vs package: yes I do require the gem at the moment but I am going to leave this issue open as a reminder that I need to fix it.
